"""empty message

Revision ID: 087d13692a90
Revises: 7e6e62f2a167
Create Date: 2020-03-13 17:05:09.257555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087d13692a90'
down_revision = '7e6e62f2a167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(('user_id', ), ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core')
    # ### end Alembic commands ###
