"""empty message

Revision ID: 170338268dd3
Revises: 4c6ce183f01f
Create Date: 2020-04-04 13:57:29.931831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '170338268dd3'
down_revision = '4c6ce183f01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plan', 'expiration',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plan', 'expiration',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
