"""empty message

Revision ID: 4c6ce183f01f
Revises: d39ffb7252c5
Create Date: 2020-04-03 17:02:41.139910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c6ce183f01f'
down_revision = 'd39ffb7252c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core', 'token')
    op.drop_column('paymongo_payment_transactions', 'credited_token')
    op.drop_column('subscription_type', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_type', sa.Column('token', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('paymongo_payment_transactions', sa.Column('credited_token', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('core', sa.Column('token', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
