"""empty message

Revision ID: 4f869b734b52
Revises: ec7dd2873cb8
Create Date: 2019-11-09 14:33:40.935757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f869b734b52'
down_revision = 'ec7dd2873cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=45),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
