"""empty message

Revision ID: 547fa4aa1536
Revises: c884c11f46ae
Create Date: 2020-04-17 13:52:54.731428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547fa4aa1536'
down_revision = 'c884c11f46ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_type', sa.Column('student_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_type', 'student_price')
    # ### end Alembic commands ###
