"""empty message

Revision ID: 5788d1f307a6
Revises: 4f869b734b52
Create Date: 2019-11-10 16:14:54.145870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5788d1f307a6'
down_revision = '4f869b734b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
