"""empty message

Revision ID: 5fb6d8fb3574
Revises: d52243a37098
Create Date: 2020-03-09 09:23:09.842781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb6d8fb3574'
down_revision = 'd52243a37098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription_plan', sa.Column('subscription_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key("fk_subscription_plan", 'subscription_plan', 'subscription_type', ['subscription_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscription_plan', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plan', sa.Column('type', mysql.VARCHAR(length=25), nullable=False))
    op.drop_constraint("fk_subscription_plan", 'subscription_plan', type_='foreignkey')
    op.drop_column('subscription_plan', 'subscription_type_id')
    op.drop_table('subscription_type')
    # ### end Alembic commands ###
