"""empty message

Revision ID: 7e6e62f2a167
Revises: 5fb6d8fb3574
Create Date: 2020-03-09 16:39:29.743338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e6e62f2a167'
down_revision = '5fb6d8fb3574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymongo_payment_transactions', sa.Column('credited_token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymongo_payment_transactions', 'credited_token')
    # ### end Alembic commands ###
