"""empty message

Revision ID: 8e62e8e8638a
Revises: 16e9e36316aa
Create Date: 2019-12-18 14:44:31.816320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e62e8e8638a'
down_revision = '16e9e36316aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymongo_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(('subscription_plan_id', ), ['subscription_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(('user_id', ), ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymongo_payment_transactions')
    # ### end Alembic commands ###
