"""empty message

Revision ID: b25c77ca8d93
Revises: 547fa4aa1536
Create Date: 2020-05-17 02:03:22.289976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25c77ca8d93'
down_revision = '547fa4aa1536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('short_description', sa.String(length=225), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('avatar_orig_filename', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('for_review', sa.Boolean(), nullable=False),
    sa.Column('quest_master_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(('quest_master_user_id', ), ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_book_tags',
    sa.Column('quest_book_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(('quest_book_id', ), ['quest_book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(('tag_id', ), ['tags.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_book_tags')
    op.drop_table('quest_book')
    op.drop_table('tags')
    # ### end Alembic commands ###
