"""empty message

Revision ID: ba42e32f9f0e
Revises: 087d13692a90
Create Date: 2020-03-19 19:21:16.261128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba42e32f9f0e'
down_revision = '087d13692a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=24), nullable=False),
    sa.Column('min_hp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('core', sa.Column('current_rank_id', sa.Integer(), nullable=False))
    op.add_column('core', sa.Column('highest_rank_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_highest_rank_id', 'core', 'ranking_system', ['highest_rank_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_current_rank_id', 'core', 'ranking_system', ['current_rank_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_highest_rank_id', 'core', type_='foreignkey')
    op.drop_constraint('fk_current_rank_id', 'core', type_='foreignkey')
    op.drop_column('core', 'highest_rank_id')
    op.drop_column('core', 'current_rank_id')
    op.drop_table('ranking_system')
    # ### end Alembic commands ###
