"""empty message

Revision ID: c884c11f46ae
Revises: 504fe8bfd6f6
Create Date: 2020-04-17 13:06:53.913535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c884c11f46ae'
down_revision = '504fe8bfd6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plan', sa.Column('is_student', sa.Boolean(), nullable=False))
    op.add_column('subscription_plan', sa.Column('is_student_renewal', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plan', 'is_student_renewal')
    op.drop_column('subscription_plan', 'is_student')
    # ### end Alembic commands ###
