"""empty message

Revision ID: d192f20257a6
Revises: 3b8699813199
Create Date: 2020-05-31 14:41:43.444968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd192f20257a6'
down_revision = '3b8699813199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_chapter_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('video_orig_filename', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quest_chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(('quest_chapter_id', ), ['quest_chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_chapter_vault')
    # ### end Alembic commands ###
